### ISSUE TITLE
[Info] Emacs persp-mode switch buffers

### ISSUE THREAD

**Issue by rokrdev** [WolfeCub/dotfiles#1]
Hi. I have copied a bit of your emacs code specifically for persp-mode. It works perfectly for my usecase(frames in terminal). 

I noticed that the buffers are filtered as per persp when using ivy. But when I use next/pervious-buffer(keybinding), I see buffers from other perspective. Is there a way to change the behaviour of next/previous-buffer. 

I am not well versed with lisp. I tried a few time to override next-buffer function, but could not get it to work with persp-mode. If you know of a way to do that please let me know. 

Thanks.

**Comment by WolfeCub** [comment]
Hey sorry for the delay,

When you're talking about next/previous buffer are you using `C-x RIGHT`? I use evil mode so I don't have many of the normal emacs functions tweaked. The easiest thing to do would be to advise the `next-buffer` (and previous) commands to use the list of buffers in the perspective rather than all of them.

I'll mess around with it a bit myself and see if I can get it working.

Thanks for the interest.

**Comment by WolfeCub** [comment]
Check [this reddit comment](https://old.reddit.com/r/emacs/comments/8uxuj1/anyone_use_perspmode_it_doesnt_seem_like_what_i/e1j6rdj/) out. It seems to be what you're after.

**Comment by rokrdev** [comment]
Hey thanks for replying. I use evil mode as well. When switching buffer, I like to bind some keybinding to switch buffer fast instead of opening ivy. 

I could not find a way to get it working per frame. The closest right now I have is this 
```
(defun my/next-buffer ()
  "next-buffer, skip * buffers
  (interactive)
  (progn
    (projectile-next-project-buffer)
    (while (string-match-p "^\*" (buffer-name))
      (projectile-next-project-buffer))
    )
  )

(defun my/previous-buffer ()
  "previous-buffer, skip * buffers"
  (interactive)
  (progn
    (projectile-previous-project-buffer)
    (while (string-match-p "^\*" (buffer-name))
      (projectile-previous-project-buffer))
    )
  )

(defun my/last-used-buffer ()
  (interactive)
  (let ((buffer-names (counsel-projectile--project-buffers)))
    (switch-to-buffer (car buffer-names) nil 'force-same-window)
    )
  )

(bind-keys*
 ( "M-}" . my/next-buffer)
 ( "M-{" . my/previous-buffer)
 ( "M-r" . my/last-used-buffer)
)
```

`projectile-next-project-buffer` falls back to `next-buffer` if its not in a project. 

This seems to work. It switches only those buffers that are shown in ivy. I will have a look at the code in the link you mentioned. The above code worked for me so I had closed the issue.

**Comment by rokrdev** [comment]
I gave up on running daemon and frames. I guess frames were not meant to work in the manner I wanted it.  I started experimenting with tabbarmode and so far it seems to work very well. We can close this issue I think
